In [1]:
import numpy as np

data = np.array([1, 1, 2, 3, 5, 8, 13])
print(data)

np.save("datafile.npy", data) # ファイルの保存
data = np.array([])           # データの消去
print(data)

data = np.load("datafile.npy") # ファイルの読み出し
print(data)

[ 1  1  2  3  5  8 13]
[]
[ 1  1  2  3  5  8 13]


In [2]:
# 2.16.2 複数のndarray型の保存

In [3]:
x0 = np.array([1, 2, 3])
x1 = np.array([10, 20, 30])
np.savez("datafile2.npz", x0=x0, x1=x1) # ファイルの保存
x0 = np.array([])                       # x0 の消去
x1 = np.array([])                       # x1 の消去
data = np.load("datafile2.npz")         # ファイル読み出し
print(data.files)                       # 格納している全変数名の表示
x0 = data["x0"]                         # x0 の取り出し
x1 = data["x1"]                         # x1 の取り出し
print(x0)
print(x1)

['x0', 'x1']
[1 2 3]
[10 20 30]
