In [2]:
# p.177 リスト 7.5
import numpy as np

storages = [24, 3, 4, 23, 10, 12]
print(storages)

# ndarray 配列を生成し、変数 np_storages に代入
np_storages = np.array(storages)

# 変数 np_storages の型
print(type(np_storages))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


In [7]:
# p.179 リスト7.9

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print("arr + arr = ", arr + arr)

# arr - arr
print("arr - arr =", arr - arr)

# arr * 3
print("arr ** 3 =", arr ** 3)

# 1 / arr
print("1 / arr =", 1 / arr)

arr + arr =  [ 4 10  6  8 16]
arr - arr = [0 0 0 0 0]
arr ** 3 = [  8 125  27  64 512]
1 / arr = [0.5        0.2        0.33333333 0.25       0.125     ]


In [9]:
# p.182 リスト 7.13

arr = np.arange(10)
print(arr)

# 変数 arr の要素のうち、3, 4, 5 だけを出力してください
print(arr[3:6])

# 変数 arr の要素のうち、3, 4, 5 を 24 に変更してください
arr[3:6] = 24
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


In [12]:
# p.183 リスト 7.15

# ndarray をそのまま別の変数に代入した場合の挙動を見て行きましょう
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# 別の変数への影響が元の変数にも影響されています
print(arr1)

# ndarray を copy() を使って別の変数に代入した場合の挙動を見て行きましょう
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# 別の変数への変更が元の変数には影響を与えていません
print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


In [19]:
# p.184 リスト 7.17

# Python のリストでスライスを用いた場合の挙動を確認しましょう
arr_List = [x for x in range(10)]
print("リスト型データです")
print("arr_List:", arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100

print("リストのスライスではコピーが作られるので、arr_List には arr_List_copy の変更が反映されません。")
print("arr_List:", arr_List)
print()

# Numpy の ndarray でスライスを用いた場合でも挙動を確認しましょう
arr_Numpy = np.arange(10)
print("Numpy の ndarray データです")
print("arr_Numpy:", arr_Numpy)
print()

arr_Numpy_view = arr_Numpy[:]
arr_Numpy_view[0] = 100

print("Numpy のスライスでは view（データが格納されている場所の情報）が代入されるので、arr_Numpy_view の変更が arr_Numpy に反映されます")
print("arr_Numpy:", arr_Numpy)
print()

# Numpy の ndarray で copy() を用いた場合での挙動を確認しましょう
arr_Numpy = np.arange(10)
print("Numpy の ndarray で copy() を用いた場合の挙動です")
print("arr_Numpy:", arr_Numpy)
print()
arr_Numpy_copy = arr_Numpy[:].copy()
arr_Numpy_copy[0] = 100

print("copy() を用いた場合は、コピーが生成されているので arr_Numpy_copy は arr_Numpy に影響を与えません")
print("arr_Numpy:", arr_Numpy)

リスト型データです
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

リストのスライスではコピーが作られるので、arr_List には arr_List_copy の変更が反映されません。
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Numpy の ndarray データです
arr_Numpy: [0 1 2 3 4 5 6 7 8 9]

Numpy のスライスでは view（データが格納されている場所の情報）が代入されるので、arr_Numpy_view の変更が arr_Numpy に反映されます
arr_Numpy: [100   1   2   3   4   5   6   7   8   9]

Numpy の ndarray で copy() を用いた場合の挙動です
arr_Numpy: [0 1 2 3 4 5 6 7 8 9]

copy() を用いた場合は、コピーが生成されているので arr_Numpy_copy は arr_Numpy に影響を与えません
arr_Numpy: [0 1 2 3 4 5 6 7 8 9]


In [30]:
# p.187 リスト 7.21

arr = np.array([2, 3, 4, 5, 6, 7])

# 変数 arr の各要素が 2 で割り切れるかどうかを示す真偽値の配列を出力してください
print(arr % 2 == 0)

# 変数 arr 各要素のうち 2 で割り切れる要素の配列を出力してください
print(arr[arr % 2 == 0])

[ True False  True False  True False]
[2 4 6]


In [37]:
# p.189 リスト 7.23

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 変数 arr の各要素を絶対値にし、変数 arr_abs に代入
arr_abs = np.abs(arr)
print(arr_abs)

# 変数 arr_abs の各要素の e のべき乗と平方根を出力
print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [44]:
# p.190 リスト7.25

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# np.unique() 関数を用いて重複をなくした配列を変数 new_arr1 に代入
new_arr1 = np.unique(arr1)
print(new_arr1)

# 変数 new_arr1 と変数 arr2 の和集合出力
print(np.union1d(new_arr1, arr2))

# 変数 new_arr1 と変数 arr2 の積集合を出力
print(np.intersect1d(new_arr1, arr2))

# 変数 new_arr1 から変数 arr2 を引いた差集合を出力
print(np.setdiff1d(new_arr1, arr2))

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]
