In [11]:
# p.194 リスト 7.29

import numpy as np

# 変数 arr に 2 次元配列を代入
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

# 変数 arr の行列の各次元の要素数を出力
print(arr.shape)

# 変数 arr を 4 行 2 列の行列に変換
print(arr.reshape((4, 2)))

print("arr =", arr)
print("numpy.ndarray.shape プロパティで次元の要素数を変換")
arr.shape = (4, 2)
print("arr =", arr)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
arr = [[1 2 3 4]
 [5 6 7 8]]
numpy.ndarray.shape プロパティで次元の要素数を変換
arr = [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
# 7.3.2 インデックス参照とスライス
# p.197 リスト 7.34

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("arr =", arr)
print()

# 変数 arr の要素のうち 3 を出力
print("3 を出力：", arr[0, 2])
print()

# 変数 arr からスライス
print(arr[1:, :2])

arr = [[1 2 3]
 [4 5 6]
 [7 8 9]]

3 を出力： 3

[[4 5]
 [7 8]]


In [19]:
# 7.3.3 axis
# p.199 リスト 7.37

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])
print("行の合計値：", arr.sum(axis=1))

行の合計値： [ 6 21 57]


In [23]:
# 7.3.4 ファンシーインデックス参照
# p.201 リスト 7.40

arr = np.arange(25).reshape(5, 5)
print(arr[[1, 3, 0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [33]:
# 7.3.5 転置行列
# p.202 リスト 7.42

arr = np.arange(10).reshape(2, 5)
print(arr)
print(arr.T)

print()
print(arr.transpose())
print()
print(np.transpose(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [40]:
# 7.3.6 ソート
# p.204 リスト 7.45

arr = np.array([[8, 4, 2], [3, 5, 1]])

# argsort() メソッドを使用
print(arr.argsort())
print()

# np.sort() 関数を用いてソートし出力
print(np.sort(arr))
print()

# sort() メソッドを用いて行でソート
arr.sort(axis=1)
print(arr)

[[2 1 0]
 [2 0 1]]

[[2 4 8]
 [1 3 5]]

[[2 4 8]
 [1 3 5]]


In [46]:
# 7.3.7 行列計算
# p.206 リスト 7.47

arr = np.arange(9).reshape(3, 3)
print(arr)

print("\n行列積の計算")
print(np.dot(arr, arr))

print()
vec = arr.reshape(9)
print(vec)
print("ノルムの計算：", np.linalg.norm(vec))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

行列積の計算
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

[0 1 2 3 4 5 6 7 8]
ノルムの計算： 14.2828568570857


In [55]:
# 7.3.8 統計関数
# p.208 リスト 7.49

print("arr")
arr = np.arange(15).reshape(3, 5)
print(arr)
print()

print("列ごとの平均")
print(np.mean(arr, axis=0))

print("\n行の合計")
print(np.sum(arr, axis=1))

print("\n最小値:", np.min(arr))

print("\nそれぞれの列の最大値のインデックス番号")
print(np.argmax(arr, axis=0))

arr
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

列ごとの平均
[5. 6. 7. 8. 9.]

行の合計
[10 35 60]

最小値: 0

それぞれの列の最大値のインデックス番号
[2 2 2 2 2]


In [60]:
# 7.3.9 ブロードキャスト
# p.209 リスト 7.52

x = np.arange(15).reshape(3, 5)
print("x\n", x)

y = np.array([np.arange(5)])
print("y\n",y)

z = x - y
print("z = x - y\n", z)

x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
y
 [[0 1 2 3 4]]
z = x - y
 [[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
