In [18]:
# p.212 リスト 7.54

import numpy as np

np.random.seed(100)

# 各要素が 0 ～ 30 の整数の行列 (5 x 3) を変数 arr に代入
arr = np.random.randint(0, 31, (5, 3))
print(arr)
print()

# 変数 arr を転置
arr = arr.T
print(arr)
print()

# 変数 arr の 2, 3, 4 列のみの行列 (3 x 3) を変数 arr1 に代入
arr1 = arr[:, 1:4]
print(arr1)
print()

# 変数 arr1 を行でソート
print("行、もとい、列でソート")
arr1.sort(axis=0) # p.204 に行でソートすると時は axis=1 と記載あるのに、添削問題では 0 にしている矛盾 → おそらく間違い
print(arr1)
print()

# 各列の平均を出力
print(arr1.mean(axis=0))

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]

[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]

[[ 7 16 20]
 [23 10  2]
 [15 30 21]]

行、もとい、列でソート
[[ 7 10  2]
 [15 16 20]
 [23 30 21]]

[15.         18.66666667 14.33333333]
