In [15]:
# p.215 リスト 7.56

import numpy as np

# 乱数を初期化
np.random.seed(0)

def make_image(m, n):
    """ 縦の大きさ、横の大きさを渡されたときに、乱数で指定の大きさの画像を生成する関数

    m
        横、列の大きさ
    n
        縦、行の大きさ
    """
    # n x m 行列の各成分を 0 ～ 5 の値でランダムに満たす
    image = np.random.randint(0, 6, (n, m))
    return image

def change_little(matrix):
    """ 渡された行列の一部を変更する関数 """
    # 与えられた行列の形を取得し、shape に代入
    shape = matrix.shape

    # 行列の各成分について、変更するかしないかをランダムに決めた上で
    # 変更する場合は 0 ～ 5 のいずれかの整数にランダムに入れ替え
    """
    a = np.random.randint(0, 2, shape)
    b = make_image(*shape)
    c = a * b
    print(a)
    print(b)
    print(c)
    print()

    return matrix - matrix * a + c
    """
    for i in range(shape[0]):
        for j in range(shape[1]):
            if np.random.randint(0, 2) == 1:
                matrix[i][j] = np.random.randint(0, 6)

    return matrix

# ランダムに画像を作成します
image1 = make_image(3, 3)
print(image1)
print()

# ランダムに変更を適用
image2 = change_little(np.copy(image1))
print(image2)
print()

# image1 と image2 の差分を計算し、image3 に代入
image3 = image1 - image2
print(image3)
print()

# image3 の各成分が絶対値である行列を求め image3 に代入
image3 = np.abs(image3)
print(image3)

[[4 5 0]
 [3 3 3]
 [1 3 5]]

[[4 5 0]
 [3 3 3]
 [0 5 5]]

[[ 0  0  0]
 [ 0  0  0]
 [ 1 -2  0]]

[[0 0 0]
 [0 0 0]
 [1 2 0]]
